In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
#원본 데이터 불러오기
raw_welfare = pd.read_spss('Koweps_h14_2019_beta4.sav')

#복사본 만들기
welfare = raw_welfare.copy()

In [3]:
#요약 통계량
welfare.describe()

,h14_id,h14_ind,h14_sn,h14_merkey,h_new,h14_cobf,h14_ws,h14_wg,h14_ws_all,h14_wg_all,...,h1416_56,h1416_60,h1416_64,h1417_1,h1417_2,h1417_3,h1417_4,h1417_5,h1417_6,h1417_7
count,6331.000000,6331.000000,6331.000000,6.331000e+03,6331.000000,83.000000,4892.000000,4892.000000,6331.000000,6331.000000,...,1248.000000,1248.000000,1248.000000,6331.000000,3497.000000,6331.000000,6331.000000,6331.000000,6331.000000,6331.000000
mean,4877.168694,3.316696,1.004423,4.877202e+07,0.227294,2.228916,1.000000,4037.572996,1.000000,3119.855583,...,1.994391,1.989583,1.781250,2.037751,1.182442,1.561681,1.192545,3.633707,1.332491,1.092560
std,2828.495321,3.477802,0.116475,2.828512e+07,0.419117,1.417016,0.810850,3273.865736,0.893369,2787.181602,...,0.074713,0.101570,0.413564,2.468569,2.164806,0.810931,0.533001,0.980825,0.659732,0.421717
min,2.000000,1.000000,1.000000,2.010100e+04,0.000000,1.000000,0.007687,31.035982,0.022656,70.683369,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2487.000000,1.000000,1.000000,2.487010e+07,0.000000,1.500000,0.390786,1577.825760,0.321405,1002.738229,...,2.000000,2.000000,2.000000,0.000000,0.000000,1.000000,1.000000,3.000000,1.000000,1.000000
50%,4812.000000,1.000000,1.000000,4.812010e+07,0.000000,2.000000,0.777355,3138.625621,0.707100,2206.050212,...,2.000000,2.000000,2.000000,1.000000,0.000000,1.000000,1.000000,4.000000,1.000000,1.000000
75%,6876.000000,7.000000,1.000000,6.876080e+07,0.000000,2.000000,1.375204,5552.487813,1.412500,4406.795497,...,2.000000,2.000000,2.000000,4.000000,1.000000,2.000000,1.000000,4.000000,2.000000,1.000000
max,9800.000000,14.000000,9.000000,9.800070e+07,1.000000,7.000000,4.017888,16222.514699,4.298926,13412.029598,...,2.000000,2.000000,2.000000,11.000000,11.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
welfare = welfare.rename(
    columns = {'h14_g3' : 'sex', #성별
               'h14_g4' : 'birth', #태어난 연도
               'h14_g10' : 'marriage_type', #혼인 상태
               'h14_g11' : 'religion', #종교
               'h14_g6' : '교육수준1', #교육수준1
               'h14_g7' : '교육수준2', #교육수준2
               'p1402_8aq1' : 'income', #월급
               'h14_eco9' : 'code_job', #직종 코드
               'h14_reg7' : 'code_region'
    }
)
welfare